import { SaleOption, Step, Community, Property, PropertyStatus } from './types';

// Communities for homepage display (simplified from data/communities.ts)
export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'abbotts-pond',
    name: "Abbott's Pond Acres",
    slug: 'abbotts-pond',
    location: 'Greenwood, DE',
    city: 'Greenwood',
    state: 'DE',
    zip: '19950',
    builder: 'Ashburn Homes',
    priceRange: '$430k - $510k',
    minPrice: 430000,
    image: 'https://drive.google.com/thumbnail?id=1oF8FDvL11zdHgdIQtmllgWIAPoV6wgZY&sz=w1200',
    status: 'Selling Fast',
    homesAvailable: 6,
    floorPlansCount: 6,
    description: 'Peaceful residential setting with spacious surroundings in Greenwood. Quick access to Route 13 and Delaware beaches.',
    is55Plus: false,
    hasClubhouse: false,
    address: 'Greenwood, DE 19950',
    schoolDistrict: 'Milford School District',
    schoolNames: ['Evelyn I. Morris Early Childhood', 'Mispillion Elementary School', 'Milford Central Academy', 'Milford Senior High School'],
    features: ['Granite Countertops', '9\' Ceilings', '2-Car Garage', 'Energy Star Certified']
  },
  {
    id: 'pinehurst-village',
    name: 'Pinehurst Village',
    slug: 'pinehurst-village',
    location: 'Felton, DE',
    city: 'Felton',
    state: 'DE',
    zip: '19943',
    builder: 'Ashburn Homes',
    priceRange: '$400k - $480k',
    minPrice: 400000,
    image: 'https://drive.google.com/thumbnail?id=1rz0seNr6VhDlx6m9LKMqAIyuGRuoAOOs&sz=w1200',
    status: 'Grand Opening',
    homesAvailable: 12,
    floorPlansCount: 6,
    description: 'Vibrant community designed for active lifestyles with carriage style garage doors and expansive floor plans.',
    is55Plus: true,
    hasClubhouse: true,
    address: '25 Belfry Dr, Felton, DE 19943',
    schoolDistrict: 'Lake Forest School District',
    schoolNames: ['Lake Forest North Elementary', 'Lake Forest Central Elementary', 'W.T. Chipman Middle School', 'Lake Forest High School'],
    features: ['8\' Unfinished Basement', 'Carriage Garage Doors', '42" Cabinets', 'Walking Trails']
  },
  {
    id: 'wiggins-mill',
    name: 'Wiggins Mill Rd',
    slug: 'wiggins-mill',
    location: 'Middletown, DE',
    city: 'Middletown',
    state: 'DE',
    zip: '19709',
    builder: 'Custom Homes by Rush',
    priceRange: '$1.3M+',
    minPrice: 1329000,
    image: 'https://drive.google.com/thumbnail?id=1GAaP2HYSxHD93csWawWXxZGM2OpG-pEO&sz=w1200',
    status: 'Closeout',
    homesAvailable: 2,
    floorPlansCount: 0,
    description: 'Exclusive custom-designed homes on spacious 1+ acre lots in the heart of Middletown.',
    is55Plus: false,
    hasClubhouse: false,
    address: 'Wiggins Mill Rd, Middletown, DE 19709',
    schoolDistrict: 'Appoquinimink School District',
    schoolNames: ['Olive B. Loss Elementary', 'Cantwell\'s Bridge Middle', 'Appoquinimink High School'],
    features: ['Custom Floor Plans', '1+ Acre Lots', 'High-End Finishes', 'Appoquinimink Schools']
  },
  {
    id: 'baywood-greens',
    name: 'Baywood Greens',
    slug: 'baywood-greens',
    location: 'Millsboro, DE',
    city: 'Millsboro',
    state: 'DE',
    zip: '19966',
    builder: 'Tunnell Companies',
    priceRange: '$305k+',
    minPrice: 305000,
    image: 'https://drive.google.com/thumbnail?id=1K4Ux3S9YqV4xNSc5IlocIlzQGzB6yyhq&sz=w1200',
    status: 'Selling Fast',
    homesAvailable: 8,
    floorPlansCount: 4,
    description: "Delaware's premier golf course community. Resort-style living just minutes from the beach.",
    is55Plus: true,
    hasClubhouse: true,
    address: '32267 Clubhouse Way, Millsboro, DE 19966',
    schoolDistrict: 'Indian River School District',
    schoolNames: ['Long Neck Elementary', 'Millsboro Middle School', 'Sussex Central High School'],
    features: ['Championship Golf', 'Resort Pool', 'Clubhouse', 'Garden Care Included']
  }
];

// Helper to generate price history
const generateHistory = (price: number) => [
  { date: '01/20/2026', event: 'Listed' as const, price: price },
  { date: '12/10/2025', event: 'Price Change' as const, price: price + 15000 },
  { date: '11/05/2025', event: 'Listed' as const, price: price + 25000 },
];

// Mock properties for Quick Move-In display
export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'The Coastal Haven - Lot 42',
    price: 645000,
    address: '123 Dune Drive',
    city: 'Lewes',
    county: 'Sussex',
    state: 'DE',
    zip: '19958',
    beds: 4,
    baths: 3.5,
    sqft: 2800,
    lotSize: '0.25 Acres',
    yearBuilt: 2024,
    builder: 'Seaside Builders',
    community: 'Cape Shores',
    status: PropertyStatus.MOVE_IN_READY,
    description: 'Stunning coastal contemporary home steps from the bay. Features an inverted floor plan to maximize views.',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1556912173-3db9963f639e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80'
    ],
    features: ['Screened Porch', 'Gourmet Kitchen', 'Smart Home Package'],
    heating: 'Forced Air, Gas',
    cooling: 'Central Air',
    parking: '2 Car Garage',
    basement: 'Finished',
    hoaFee: 150,
    taxAssessment: 3200,
    schools: [
      { name: 'Shields Elementary', rating: 8, level: 'Elementary', distance: '1.2 mi' },
      { name: 'Beacon Middle', rating: 7, level: 'Middle', distance: '2.4 mi' },
      { name: 'Cape Henlopen High', rating: 9, level: 'High', distance: '3.1 mi' }
    ],
    completionDate: 'Immediate',
    mlsId: 'DESU2055123',
    listingBrokerage: 'Compass RE',
    listingAgent: 'Rush Home Team',
    listingAgentPhone: '302-219-6707',
    brokeragePhone: '302-219-6707',
    lastUpdated: 'Jan 26, 2026',
    priceHistory: generateHistory(645000)
  },
  {
    id: '2',
    title: 'The Executive Colonial - Lot 8',
    price: 750000,
    address: '9 Presidential Dr',
    city: 'Newark',
    county: 'New Castle',
    state: 'DE',
    zip: '19711',
    beds: 4,
    baths: 3.5,
    sqft: 3100,
    lotSize: '0.50 Acres',
    yearBuilt: 2024,
    builder: 'Heritage Builders',
    community: 'Independence Woods',
    status: PropertyStatus.MOVE_IN_READY,
    description: 'Classic colonial architecture meets modern energy efficiency. Located in the coveted Newark Charter radius.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-e328d4de4bf7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfe1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80'
    ],
    features: ['Charter School Radius', 'Morning Room', 'Composite Deck'],
    heating: 'Forced Air, Electric',
    cooling: 'Central Air',
    parking: '2 Car Garage',
    basement: 'Unfinished',
    hoaFee: 75,
    taxAssessment: 4100,
    schools: [
      { name: 'Downes Elementary', rating: 8, level: 'Elementary', distance: '1.2 mi' },
      { name: 'Shue-Medill Middle', rating: 5, level: 'Middle', distance: '2.4 mi' },
      { name: 'Newark High', rating: 5, level: 'High', distance: '3.1 mi' }
    ],
    completionDate: 'Immediate',
    mlsId: 'DENC2094881',
    listingBrokerage: 'Compass RE',
    listingAgent: 'Rush Home Team',
    listingAgentPhone: '302-219-6707',
    brokeragePhone: '302-219-6707',
    lastUpdated: 'Jan 26, 2026',
    priceHistory: generateHistory(750000)
  },
  {
    id: '3',
    title: 'City View Townhome - Unit 4B',
    price: 450000,
    address: '88 Market St',
    city: 'Wilmington',
    county: 'New Castle',
    state: 'DE',
    zip: '19801',
    beds: 3,
    baths: 2.5,
    sqft: 1900,
    lotSize: '0.05 Acres',
    yearBuilt: 2023,
    builder: 'CityLife Construction',
    community: 'Riverfront Enclave',
    status: PropertyStatus.MODEL_HOME,
    description: 'Luxury townhome living on the Wilmington Riverfront. Roof deck options available with city skyline views.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80'
    ],
    features: ['Roof Deck', 'Quartz Countertops', 'Walkability'],
    heating: 'Heat Pump',
    cooling: 'Central Air',
    parking: '1 Car Garage',
    basement: 'None',
    hoaFee: 220,
    taxAssessment: 2800,
    schools: [
      { name: 'Pulaski Elementary', rating: 3, level: 'Elementary', distance: '1.2 mi' },
      { name: 'Bayard Middle', rating: 2, level: 'Middle', distance: '2.4 mi' },
      { name: 'Christiana High', rating: 3, level: 'High', distance: '3.1 mi' }
    ],
    completionDate: 'Model Open',
    mlsId: 'DENC2011234',
    listingBrokerage: 'Compass RE',
    listingAgent: 'Rush Home Team',
    listingAgentPhone: '302-219-6707',
    brokeragePhone: '302-219-6707',
    lastUpdated: 'Jan 26, 2026',
    priceHistory: generateHistory(450000)
  },
  {
    id: '4',
    title: 'The Farmhouse - Lot 12',
    price: 825000,
    address: '45 Country Lane',
    city: 'Middletown',
    county: 'New Castle',
    state: 'DE',
    zip: '19709',
    beds: 5,
    baths: 4.5,
    sqft: 3800,
    lotSize: '1.2 Acres',
    yearBuilt: 2024,
    builder: 'Legacy Homes',
    community: 'Appoquinimink Estates',
    status: PropertyStatus.UNDER_CONSTRUCTION,
    description: 'Modern farmhouse design with wrap-around porch and black window frames. Ready in 45 days.',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1598228723793-52759bba239c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80'
    ],
    features: ['Wrap-around Porch', 'Finished Basement', '3-Car Garage'],
    heating: 'Forced Air, Propane',
    cooling: 'Central Air',
    parking: '3 Car Garage',
    basement: 'Finished',
    hoaFee: 100,
    taxAssessment: 4500,
    schools: [
      { name: 'Cedar Lane Elementary', rating: 9, level: 'Elementary', distance: '1.2 mi' },
      { name: 'Redding Middle', rating: 8, level: 'Middle', distance: '2.4 mi' },
      { name: 'Appoquinimink High', rating: 9, level: 'High', distance: '3.1 mi' }
    ],
    completionDate: '45 Days',
    mlsId: 'DENC2055678',
    listingBrokerage: 'Compass RE',
    listingAgent: 'Rush Home Team',
    listingAgentPhone: '302-219-6707',
    brokeragePhone: '302-219-6707',
    lastUpdated: 'Jan 26, 2026',
    priceHistory: generateHistory(825000)
  },
  {
    id: '5',
    title: 'Bayside Cottage',
    price: 599000,
    address: '22 Marina Way',
    city: 'Long Neck',
    county: 'Sussex',
    state: 'DE',
    zip: '19966',
    beds: 3,
    baths: 2,
    sqft: 1800,
    lotSize: '0.15 Acres',
    yearBuilt: 2024,
    builder: 'Seaside Builders',
    community: 'Baywood',
    status: PropertyStatus.MOVE_IN_READY,
    description: 'Perfect vacation home or retirement retreat. Includes boat slip access.',
    images: [
      'https://images.unsplash.com/photo-1575517111478-7f603f0547bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80'
    ],
    features: ['Boat Slip', 'Single Level Living', 'Water Views'],
    heating: 'Heat Pump',
    cooling: 'Central Air',
    parking: 'Driveway',
    basement: 'None',
    hoaFee: 300,
    taxAssessment: 2100,
    schools: [
      { name: 'Long Neck Elementary', rating: 6, level: 'Elementary', distance: '1.2 mi' },
      { name: 'Millsboro Middle', rating: 6, level: 'Middle', distance: '2.4 mi' },
      { name: 'Sussex Central High', rating: 6, level: 'High', distance: '3.1 mi' }
    ],
    completionDate: 'Immediate',
    mlsId: 'DESU2011999',
    listingBrokerage: 'Compass RE',
    listingAgent: 'Rush Home Team',
    listingAgentPhone: '302-219-6707',
    brokeragePhone: '302-219-6707',
    lastUpdated: 'Jan 26, 2026',
    priceHistory: generateHistory(599000)
  },
  {
    id: '6',
    title: 'The Clayton Traditional',
    price: 425000,
    address: '100 Wheatfield Dr',
    city: 'Smyrna',
    county: 'Kent',
    state: 'DE',
    zip: '19977',
    beds: 4,
    baths: 2.5,
    sqft: 2400,
    lotSize: '0.20 Acres',
    yearBuilt: 2025,
    builder: 'Benchmark Builders',
    community: 'Cambria Village',
    status: PropertyStatus.TO_BE_BUILT,
    description: 'Affordable luxury in the heart of Smyrna. Open concept living with easy access to Route 1.',
    images: [
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80'
    ],
    features: ['Open Concept', '2-Car Garage', 'Energy Star Certified'],
    heating: 'Natural Gas',
    cooling: 'Central Air',
    parking: '2 Car Garage',
    basement: 'Unfinished',
    hoaFee: 50,
    taxAssessment: 2900,
    schools: [
      { name: 'Smyrna Elementary', rating: 7, level: 'Elementary', distance: '1.2 mi' },
      { name: 'Smyrna Middle', rating: 7, level: 'Middle', distance: '2.4 mi' },
      { name: 'Smyrna High', rating: 7, level: 'High', distance: '3.1 mi' }
    ],
    completionDate: 'Fall 2025',
    mlsId: 'DEKT2004321',
    listingBrokerage: 'Compass RE',
    listingAgent: 'Rush Home Team',
    listingAgentPhone: '302-219-6707',
    brokeragePhone: '302-219-6707',
    lastUpdated: 'Jan 26, 2026',
    priceHistory: generateHistory(425000)
  }
];

export const SALE_OPTIONS: SaleOption[] = [
  {
    id: 'immediate',
    title: 'RUSH HOME IMMEDIATE',
    subtitle: 'Instant Cash Offer',
    description: 'Instant cash offer with closing in as few as 14 days.',
    bestFor: 'Maximum speed & certainty',
    features: [
      'Close in as few as 14 days',
      'No staging or repairs needed',
      'Leaseback option available',
      'Avoid market uncertainty'
    ]
  },
  {
    id: 'advantage',
    title: 'RUSH HOME ADVANTAGE',
    subtitle: 'Maximize Equity',
    description: 'Access majority of proceeds upfront while we handle improvements.',
    bestFor: 'Convenience + equity capture',
    features: [
      'Access funds immediately',
      'We manage improvements',
      'Capture more equity',
      'Hassle-free transition'
    ]
  },
  {
    id: 'flex',
    title: 'RUSH HOME FLEX',
    subtitle: 'Guaranteed Backup',
    description: '150-day guaranteed backup offer while you sell traditionally.',
    bestFor: 'Buy before you sell',
    features: [
      '150-day guaranteed offer',
      'Buy your next home first',
      'Compete without contingency',
      'Try traditional sale first'
    ],
    highlight: true
  }
];

export const FLEX_STEPS: Step[] = [
  {
    number: '01',
    title: 'Get a Guaranteed Backup Offer',
    description: 'We secure a firm purchase contract on your current home, valid for 150 days.'
  },
  {
    number: '02',
    title: 'Shop with Confidence',
    description: 'Make non-contingent offers on your dream home, knowing your current home will sell.'
  },
  {
    number: '03',
    title: 'List Traditionally',
    description: 'We market your home to maximize value. If it sells before the backup deadline, you keep the higher price.'
  },
  {
    number: '04',
    title: 'Guaranteed Sale',
    description: "If your home doesn't sell traditionally, the guaranteed backup offer activates automatically."
  }
];
