'use client';

import React, { useEffect, useState } from 'react';

const QuickBuyEmbed: React.FC = () => {
  const [iframeHeight, setIframeHeight] = useState(80); 

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data && event.data.type === 'QUICKBUY_RESIZE') {
        setIframeHeight(event.data.height);
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);

  const iframeHtml = `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
        <style>
          /* 1. Base Styles */
          body { 
            margin: 0; 
            padding: 0; 
            font-family: 'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            overflow: hidden; 
            background: transparent;
          }
          
          /* 2. THE LAYOUT FIX: Force Side-by-Side */
          .ilist-content {
            border-radius: 12px;
            overflow: hidden;
            border: 1px solid #e5e5e5;
          }

          /* Target the form generated by the script inside .ilist-content */
          .ilist-content form, 
          .ilist-content > div {
             display: flex !important;
             flex-direction: row !important;
             align-items: stretch !important;
             gap: 0 !important;
             width: 100% !important;
          }

          /* 3. Input Field Styling */
          .ilist-content input {
             flex-grow: 1 !important;
             margin: 0 !important;
             width: auto !important;
             border: none !important;
             border-radius: 0 !important;
             padding: 14px 16px !important;
             font-size: 16px !important;
             font-family: 'Montserrat', sans-serif !important;
          }

          .ilist-content input:focus {
             outline: none !important;
          }

          /* 4. Button Styling */
          .ilist-content button {
             width: auto !important;
             white-space: nowrap !important;
             margin: 0 !important;
             display: flex !important;
             align-items: center !important;
             justify-content: center !important;
             padding: 14px 24px !important;
             height: auto !important;
             background: #000000 !important;
             background-color: #000000 !important;
             color: #ffffff !important;
             border: none !important;
             border-radius: 0 !important;
             font-weight: 600 !important;
             font-family: 'Montserrat', sans-serif !important;
             cursor: pointer !important;
          }

          .ilist-content button:hover {
             background: #262626 !important;
             background-color: #262626 !important;
          }

          /* Stack on mobile screens */
          @media (max-width: 480px) {
            .ilist-content form,
            .ilist-content > div {
               flex-direction: column !important;
            }
            .ilist-content input, 
            .ilist-content button {
               width: 100% !important;
            }
          }
        </style>
      </head>
      <body>
        
        <div class="ilist-content"></div>

        <script src="https://rushhome.quickbuyoffer.com/scripts/falcon/auto-address.js?v=2.01"></script>

        <script>
          // Button Text Updater
          setInterval(() => {
            const buttons = document.querySelectorAll('button');
            buttons.forEach(btn => {
              if (btn.textContent && btn.textContent.includes('Get Value')) {
                btn.textContent = 'Get Offer';
              }
            });
          }, 500);

          // Resizer Logic
          const sendHeight = () => {
            const height = document.body.scrollHeight;
            window.parent.postMessage({ type: 'QUICKBUY_RESIZE', height: height }, '*');
          };
          window.addEventListener('load', sendHeight);
          const observer = new ResizeObserver(sendHeight);
          observer.observe(document.body);
          setInterval(sendHeight, 1000);
        </script>
      </body>
    </html>
  `;

  return (
    <div style={{ width: '100%', minHeight: '60px' }}>
      <iframe
        srcDoc={iframeHtml}
        title="QuickBuy Offer Widget"
        style={{
          width: '100%',
          height: `${iframeHeight}px`,
          border: 'none',
          transition: 'height 0.2s ease', 
          display: 'block'
        }}
        scrolling="no" 
      />
    </div>
  );
};

export default QuickBuyEmbed;
